/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import controller.ClientController;
import model.BookedTicket;

import java.awt.Component;
import java.math.BigDecimal;
import java.rmi.RemoteException;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Locale.Category;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Admin;
import model.Ticket;
import model.User;
import service.BookedTicketService;

import service.TicketService;


/**
 *
 * @author Serge B
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
 public AdminPanel() throws RemoteException {
    initComponents();

    // Load remote services via RMI
    BookedTicketService bookedTicketService = ClientController.getBookedTicketService();

    // Add selection listener to BookedTable
    BookedTable.getSelectionModel().addListSelectionListener(e -> {
        int selectedRow = BookedTable.getSelectedRow();
        if (selectedRow != -1) {
            // Get the Ticket ID and Username from the selected row
            String ticketId = BookedTable.getValueAt(selectedRow, 0).toString(); // assuming ID is in column 0
            String username = BookedTable.getValueAt(selectedRow, 1).toString(); // assuming username is in column 1

            // Call method to display the selected ticket details
            displaySelectedTicketDetails(username, ticketId);
        }
    });

    // Load data into tables using RMI
    loadTicketsToTable();         // This should use TicketService via RMI
    loadUsersTable();            // This should use UserService via RMI
    loadBookedTicketsToTable();  // This should use BookedTicketService via RMI

    makeTableRowsSelectable();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Tickets = new javax.swing.JButton();
        Booked = new javax.swing.JButton();
        Users = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        destinationTxt = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        orginTxt = new javax.swing.JTextField();
        seatTxt = new javax.swing.JTextField();
        DateTxt = new javax.swing.JTextField();
        Category = new javax.swing.JComboBox<>();
        addbtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TicketTable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        SearchTxt = new javax.swing.JTextField();
        Searchbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        searchTxt = new javax.swing.JTextField();
        serchbtnu = new javax.swing.JButton();
        deletbtnu = new javax.swing.JButton();
        makeadmin = new javax.swing.JButton();
        removeadmin = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        searchbtbb = new javax.swing.JButton();
        searchbtxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        BookedTable = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaReceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(0, 102, 0));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/3d-house.png"))); // NOI18N
        home.setText("HOME");
        home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/admin2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tickets.setBackground(new java.awt.Color(255, 255, 255));
        Tickets.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Tickets.setForeground(new java.awt.Color(0, 102, 0));
        Tickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/airplane-ticket.png"))); // NOI18N
        Tickets.setText("Tickets");
        Tickets.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketsActionPerformed(evt);
            }
        });

        Booked.setBackground(new java.awt.Color(255, 255, 255));
        Booked.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Booked.setForeground(new java.awt.Color(0, 102, 0));
        Booked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/boarding.png"))); // NOI18N
        Booked.setText("Booked Tickets");
        Booked.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Booked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookedActionPerformed(evt);
            }
        });

        Users.setBackground(new java.awt.Color(255, 255, 255));
        Users.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Users.setForeground(new java.awt.Color(0, 102, 0));
        Users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/user.png"))); // NOI18N
        Users.setText("Users");
        Users.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Booked, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(Users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(Tickets, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Booked, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 51));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(51, 153, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 0));
        jLabel3.setText("Ticket Management");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Orgin");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("destination");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Date");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("Price");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Class");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Seat");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        destinationTxt.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        destinationTxt.setForeground(new java.awt.Color(0, 0, 255));
        destinationTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        priceTxt.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        priceTxt.setForeground(new java.awt.Color(0, 0, 255));
        priceTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        orginTxt.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        orginTxt.setForeground(new java.awt.Color(0, 0, 255));
        orginTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        seatTxt.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        seatTxt.setForeground(new java.awt.Color(0, 0, 255));
        seatTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTxtActionPerformed(evt);
            }
        });

        Category.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Category.setForeground(new java.awt.Color(102, 153, 0));
        Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Business", "Economy", "First", " " }));
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });

        addbtn.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        addbtn.setForeground(new java.awt.Color(0, 153, 0));
        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/add.png"))); // NOI18N
        addbtn.setText("ADD");
        addbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(orginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(seatTxt)
                                    .addComponent(Category, javax.swing.GroupLayout.Alignment.TRAILING, 0, 166, Short.MAX_VALUE)
                                    .addComponent(destinationTxt)
                                    .addComponent(DateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(priceTxt))))
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(addbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(orginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(destinationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatTxt)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TicketTable.setBackground(new java.awt.Color(255, 255, 153));
        TicketTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TicketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Orgin", "Destination", "Date", "Price", "Class", "Seat"
            }
        ));
        TicketTable.setGridColor(new java.awt.Color(51, 153, 0));
        TicketTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TicketTableComponentAdded(evt);
            }
        });
        TicketTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TicketTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TicketTable);

        jPanel10.setBackground(new java.awt.Color(255, 255, 153));

        SearchTxt.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        SearchTxt.setForeground(new java.awt.Color(0, 0, 255));
        SearchTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Searchbtn.setBackground(new java.awt.Color(255, 255, 153));
        Searchbtn.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        Searchbtn.setForeground(new java.awt.Color(0, 153, 0));
        Searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        Searchbtn.setText("Search");
        Searchbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(0, 153, 0));
        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/cancel.png"))); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(0, 153, 0));
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/updated.png"))); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 153, 0));
        jLabel10.setText("Options");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(71, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Searchbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(SearchTxt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(4, 4, 4))))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("TICKET MANAGEMENT", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userTable.setBackground(new java.awt.Color(255, 255, 153));
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "USERNAME", "PHONE NUMBER", "ADDRESS", "PASSWORD", "ROLE"
            }
        ));
        userTable.setGridColor(new java.awt.Color(102, 153, 0));
        userTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                userTableComponentAdded(evt);
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(userTable);

        jPanel15.setBackground(new java.awt.Color(255, 255, 153));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setForeground(new java.awt.Color(204, 0, 204));

        searchTxt.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        searchTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        serchbtnu.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        serchbtnu.setForeground(new java.awt.Color(0, 153, 0));
        serchbtnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        serchbtnu.setText("Search");
        serchbtnu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        serchbtnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchbtnuActionPerformed(evt);
            }
        });

        deletbtnu.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        deletbtnu.setForeground(new java.awt.Color(0, 153, 0));
        deletbtnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/cancel.png"))); // NOI18N
        deletbtnu.setText("Remove User");
        deletbtnu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletbtnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletbtnuActionPerformed(evt);
            }
        });

        makeadmin.setBackground(new java.awt.Color(255, 255, 255));
        makeadmin.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        makeadmin.setForeground(new java.awt.Color(0, 153, 0));
        makeadmin.setText("MAKE ADMIN");
        makeadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeadminActionPerformed(evt);
            }
        });

        removeadmin.setBackground(new java.awt.Color(255, 255, 255));
        removeadmin.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        removeadmin.setForeground(new java.awt.Color(51, 153, 0));
        removeadmin.setText("REMOVE ADMIN");
        removeadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeadminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(makeadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serchbtnu, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(deletbtnu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serchbtnu)))
                    .addComponent(makeadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(deletbtnu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(removeadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 0));
        jLabel12.setText("UserMangement");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("USER MANAGEMENT", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel13.setBackground(new java.awt.Color(255, 255, 204));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 0));
        jLabel11.setText("BOOKED TICKETS");

        jPanel14.setBackground(new java.awt.Color(255, 255, 153));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setForeground(new java.awt.Color(204, 0, 204));

        searchbtbb.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        searchbtbb.setForeground(new java.awt.Color(0, 153, 0));
        searchbtbb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        searchbtbb.setText("Search");
        searchbtbb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchbtbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtbbActionPerformed(evt);
            }
        });

        searchbtxt.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        searchbtxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(searchbtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchbtbb, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbtbb)
                    .addComponent(searchbtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BookedTable.setBackground(new java.awt.Color(255, 255, 153));
        BookedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TICKET ID", "PASSENGER", "PHONE NUMBER", "ADDRESS", "ORGIN", "DESTINATION"
            }
        ));
        BookedTable.setGridColor(new java.awt.Color(102, 153, 0));
        BookedTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                BookedTableComponentAdded(evt);
            }
        });
        jScrollPane3.setViewportView(BookedTable);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 0));
        jLabel13.setText("Ticket Receipt");

        jTextAreaReceipt.setColumns(20);
        jTextAreaReceipt.setRows(5);
        jTextAreaReceipt.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextAreaReceiptComponentAdded(evt);
            }
        });
        jScrollPane5.setViewportView(jTextAreaReceipt);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane5)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("BOOKED TICKETS", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatTxtActionPerformed

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryActionPerformed

    private void TicketTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TicketTableComponentAdded
        try {
            // TODO add your handling code here:

            loadTicketsToTable();
        } catch (RemoteException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TicketTableComponentAdded

    private void TicketTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TicketTableMouseClicked
            int selectedRow = TicketTable.getSelectedRow();

    if (selectedRow == -1) return;

    try {
        // Get the ticket ID from the selected row
        String ticketId = TicketTable.getValueAt(selectedRow, 0).toString().trim();

        // Use RMI service to fetch ticket by ID
        TicketService ticketService = ClientController.getTicketService();
        Ticket ticketToUpdate = ticketService.searchById(ticketId); // Remote call

        if (ticketToUpdate != null) {
            // Populate form fields
            orginTxt.setText(ticketToUpdate.getOrigin());
            destinationTxt.setText(ticketToUpdate.getDestination());
            DateTxt.setText(ticketToUpdate.getDate() != null ? ticketToUpdate.getDate().toString() : "");
            priceTxt.setText(String.valueOf(ticketToUpdate.getPrice()));
            Category.setSelectedItem(ticketToUpdate.getCategory());
            seatTxt.setText(ticketToUpdate.getSeat());
        } else {
            JOptionPane.showMessageDialog(null, "Ticket not found!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error retrieving ticket: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_TicketTableMouseClicked

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
     // Get and trim the input values
    String origin = orginTxt.getText().trim();
    String destination = destinationTxt.getText().trim();
    Date date = null; try { date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(DateTxt.getText()); } catch(Exception ex) { javax.swing.JOptionPane.showMessageDialog(this,"Invalid date. Use yyyy-MM-dd"); return; }
    String seat = seatTxt.getText().trim();
    String priceStr = priceTxt.getText().trim();
    String selectedCategory = (String) Category.getSelectedItem();  // if categoryTxt is a JTextField

    // Validate origin
    if (origin.isEmpty() || origin.length() < 3) {
        JOptionPane.showMessageDialog(null, "Origin must be at least 3 characters.");
        return;
    }

    // Validate destination
    if (destination.isEmpty() || destination.length() < 3) {
        JOptionPane.showMessageDialog(null, "Destination must be at least 3 characters.");
        return;
    }

    // Validate date is not in the past
    if (date == null) {
        JOptionPane.showMessageDialog(null, "Please select a valid date.");
        return;
    } else {
        Date today = new Date();
        if (date.before(today)) {
            JOptionPane.showMessageDialog(null, "Date cannot be in the past.");
            return;
        }
    }

    // Validate seat format
    if (!seat.matches("^[A-Z]{1}[0-9]{1,3}$")) {
        JOptionPane.showMessageDialog(null, "Seat format must be one letter followed by 1 to 3 digits (e.g., A1, B12).");
        return;
    }

    // Validate price
    BigDecimal price;
    try {
        price = new BigDecimal(priceStr);
        if (price.compareTo(BigDecimal.ZERO) < 0) {
            JOptionPane.showMessageDialog(null, "Price cannot be negative.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid input! Please enter a valid number for the price.");
        return;
    }

    // Validate category as string
    if (!(selectedCategory.equalsIgnoreCase("Economy") 
          || selectedCategory.equalsIgnoreCase("Business") 
          || selectedCategory.equalsIgnoreCase("First"))) {
        JOptionPane.showMessageDialog(null, "Category must be Economy, Business, or First.");
        return;
    }

    // Create Ticket object
    Ticket ticket = new Ticket();
    ticket.setOrigin(origin);
    ticket.setDestination(destination);
    ticket.setDate(new java.sql.Date(date.getTime())); // Convert to SQL Date
    ticket.setPrice(price);
    ticket.setCategory(selectedCategory);  // assign string category directly
    ticket.setSeat(seat);

    // Use RMI to call the server's TicketService
    try {
        boolean result = ClientController.ticketService.addTicket(ticket);
        if (result) {
            JOptionPane.showMessageDialog(null, "Ticket added successfully!");
            clear();
            loadTicketsToTable();
        } else {
            JOptionPane.showMessageDialog(null, "Failed to add ticket. Please try again.");
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Server error: " + ex.getMessage());
    }
       
    }//GEN-LAST:event_addbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
   int selectedRow = TicketTable.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(null, "Please select a ticket to update.");
    return;
}

String ticketId = TicketTable.getValueAt(selectedRow, 0).toString().trim();

try {
    TicketService ticketService = ClientController.getTicketService();
    Ticket ticketToUpdate = ticketService.searchById(ticketId);

    if (ticketToUpdate == null) {
        JOptionPane.showMessageDialog(null, "Ticket not found.");
        return;
    }
    
    
       String origin = orginTxt.getText().trim();
    String destination = destinationTxt.getText().trim();
    Date date = null; try { date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(DateTxt.getText()); } catch(Exception ex) { javax.swing.JOptionPane.showMessageDialog(this,"Invalid date. Use yyyy-MM-dd"); return; }
    String seat = seatTxt.getText().trim();
    String priceStr = priceTxt.getText().trim();
    String selectedCategory = (String) Category.getSelectedItem();  // if categoryTxt is a JTextField

    // Validate origin
    if (origin.isEmpty() || origin.length() < 3) {
        JOptionPane.showMessageDialog(null, "Origin must be at least 3 characters.");
        return;
    }

    // Validate destination
    if (destination.isEmpty() || destination.length() < 3) {
        JOptionPane.showMessageDialog(null, "Destination must be at least 3 characters.");
        return;
    }

    // Validate date is not in the past
    if (date == null) {
        JOptionPane.showMessageDialog(null, "Please select a valid date.");
        return;
    } else {
        Date today = new Date();
        if (date.before(today)) {
            JOptionPane.showMessageDialog(null, "Date cannot be in the past.");
            return;
        }
    }

    // Validate seat format
    if (!seat.matches("^[A-Z]{1}[0-9]{1,3}$")) {
        JOptionPane.showMessageDialog(null, "Seat format must be one letter followed by 1 to 3 digits (e.g., A1, B12).");
        return;
    }

    // Validate price
    BigDecimal price;
    try {
        price = new BigDecimal(priceStr);
        if (price.compareTo(BigDecimal.ZERO) < 0) {
            JOptionPane.showMessageDialog(null, "Price cannot be negative.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid input! Please enter a valid number for the price.");
        return;
    }

    // Validate category as string
    if (!(selectedCategory.equalsIgnoreCase("Economy") 
          || selectedCategory.equalsIgnoreCase("Business") 
          || selectedCategory.equalsIgnoreCase("First"))) {
        JOptionPane.showMessageDialog(null, "Category must be Economy, Business, or First.");
        return;
    }

    // Create Ticket object
    Ticket ticket = new Ticket();
    ticket.setOrigin(origin);
    ticket.setDestination(destination);
    ticket.setDate(new java.sql.Date(date.getTime())); // Convert to SQL Date
    ticket.setPrice(price);
    ticket.setCategory(selectedCategory);  // assign string category directly
    ticket.setSeat(seat);

    

    boolean result = ticketService.updateTicket(ticket);

    if (result) {
        JOptionPane.showMessageDialog(null, "Ticket updated successfully!");
        clear();
        loadTicketsToTable();
    } else {
        JOptionPane.showMessageDialog(null, "Failed to update ticket. Please try again.");
    }

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error updating ticket: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_updatebtnActionPerformed

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
      String searchTicketId = SearchTxt.getText().trim();  // Search field input

    if (searchTicketId.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter a Ticket ID to search.");
        return;
    }

    try {
        // Use RMI to get the TicketService
        TicketService ticketService = ClientController.getTicketService();

        // Search for the ticket via RMI
        Ticket ticket = ticketService.searchById(searchTicketId);

        // Clear the table before displaying results
        DefaultTableModel model = (DefaultTableModel) TicketTable.getModel();
        model.setRowCount(0);

        if (ticket != null) {
            model.addRow(new Object[] {
                ticket.getTicketId(),
                ticket.getOrigin(),
                ticket.getDestination(),
                ticket.getDate(),
                ticket.getPrice(),
                ticket.getCategory(),
                ticket.getSeat()
            });
        } else {
            JOptionPane.showMessageDialog(null, "Ticket with ID " + searchTicketId + " not found.");
            loadTicketsToTable(); // Load all if not found
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error searching ticket: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_SearchbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
      int selectedRow = TicketTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a ticket to delete.");
        return;
    }

    // Get ticket ID from selected row
    String ticketId = TicketTable.getValueAt(selectedRow, 0).toString();

    // Confirm deletion
    int confirmation = JOptionPane.showConfirmDialog(
        null,
        "Are you sure you want to delete this ticket?",
        "Delete Ticket",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE
    );

    if (confirmation == JOptionPane.YES_OPTION) {
        try {
            // Use RMI TicketService
            TicketService ticketService = ClientController.getTicketService();

            // Call the remote method to delete
            boolean result = ticketService.deleteTicketById(ticketId);

            if (result) {
                JOptionPane.showMessageDialog(null, "Ticket deleted successfully!");
                loadTicketsToTable(); // Refresh table
                clear(); // Clear form
            } else {
                JOptionPane.showMessageDialog(null, "Failed to delete ticket. Please try again.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error deleting ticket: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        System.out.println("Ticket deletion cancelled.");
    }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void TicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketsActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_TicketsActionPerformed

    private void BookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookedActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_BookedActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_UsersActionPerformed

    private void searchbtbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtbbActionPerformed
       String usernameToSearch = searchbtxt.getText().trim();

    if (usernameToSearch.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a username to search.");
        return;
    }

    try {
        // Make sure ClientController.init() was called before this (e.g., on app startup)
        List<BookedTicket> bookedTickets = ClientController.getBookedTicketService()
                .getBookedTicketsByUsername(usernameToSearch);

        if (bookedTickets == null || bookedTickets.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No tickets found for the username: " + usernameToSearch);

            // Reload all tickets after the user clicks "OK"
            loadBookedTicketsToTable();
        } else {
            // Update your table with the search results
             loadBookedTicketsToTable();
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error occurred while fetching tickets: " + e.getMessage());
    }
    }//GEN-LAST:event_searchbtbbActionPerformed

    private void BookedTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_BookedTableComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_BookedTableComponentAdded

    private void userTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_userTableComponentAdded
        // TODO add your handling code here:
        loadUsersTable();

    }//GEN-LAST:event_userTableComponentAdded

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userTableMouseClicked

    private void serchbtnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchbtnuActionPerformed
      String username = searchTxt.getText().trim();

    if (username.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter a username to search.");
        return;
    }

    try {
        // Make sure ClientController.init() has been called during app startup
        User user = ClientController.getUserService().getUserByUsername(username);

        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        model.setRowCount(0); // Clear current table content

        if (user != null) {
            model.addRow(new Object[]{
                user.getUsername(),
                user.getPhoneNumber(),
                user.getAddress(),
                user.getPassword()
            });
        } else {
            JOptionPane.showMessageDialog(null, "No user found with username: " + username);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error occurred while searching user: " + e.getMessage());
    }
    }//GEN-LAST:event_serchbtnuActionPerformed

    private void deletbtnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletbtnuActionPerformed
     int selectedRow = userTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a user to delete.");
        return;
    }

    String username = userTable.getValueAt(selectedRow, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(null,
        "Are you sure you want to delete user: " + username + "?",
        "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // Make sure ClientController.init() was called earlier
            boolean success = ClientController.getUserService().deleteUser(username);

            if (success) {
                JOptionPane.showMessageDialog(null, "User deleted successfully.");
                loadUsersTable(); // Refresh table after deletion
            } else {
                JOptionPane.showMessageDialog(null, "Failed to delete user. Please try again.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error occurred while deleting user: " + e.getMessage());
        }
    } else {
        System.out.println("User deletion cancelled.");
    }

    }//GEN-LAST:event_deletbtnuActionPerformed

    private void jTextAreaReceiptComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextAreaReceiptComponentAdded
        // TODO add your handling code here:
       int selectedRow = BookedTable.getSelectedRow();
    if (selectedRow != -1) {
        // Assuming the username is in the second column (index 1)
        String username = BookedTable.getValueAt(selectedRow, 1).toString(); // adjust if needed
        String ticketId = BookedTable.getValueAt(selectedRow, 0).toString(); // assuming ID is in column 0
        // Call the method with both ticketId and username
        displaySelectedTicketDetails(username, ticketId);
    }
    }//GEN-LAST:event_jTextAreaReceiptComponentAdded

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
        
         Airplane home = new Airplane();
         home.setVisible(true);
         
         currentFrame.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void makeadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeadminActionPerformed
              int selectedRow = userTable.getSelectedRow();

    if (selectedRow != -1) {
        String username = userTable.getValueAt(selectedRow, 0).toString();

        try {
            // Use remote AdminService and UserService
            if (ClientController.getAdminService().isAlreadyAdmin(username)) {
                JOptionPane.showMessageDialog(this, "User '" + username + "' is already an admin.");
            } else {
                // Add admin record remotely
                Admin admin = new Admin();
                admin.setUsername(username);
                ClientController.getAdminService().createAdmin(admin);

                JOptionPane.showMessageDialog(this, "User '" + username + "' added to admins table.");
            }

            boolean updated = ClientController.getUserService().updateRoleToAdmin(username);

            if (updated) {
                JOptionPane.showMessageDialog(this, "User '" + username + "' role updated to admin.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update role.");
            }

            loadUsersTable(); // Refresh user table after changes

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred while making user admin: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a user from the table.");
    }
    }//GEN-LAST:event_makeadminActionPerformed

    private void removeadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeadminActionPerformed
            int selectedRow = userTable.getSelectedRow();

    if (selectedRow != -1) {
        String username = userTable.getValueAt(selectedRow, 0).toString();

        try {
            // Create admin object to delete
            Admin admin = new Admin();
            admin.setUsername(username);

            // Call remote delete method (returns Admin object or null)
            Admin deletedAdmin = ClientController.getAdminService().deleteAdmin(admin);

            if (deletedAdmin != null) {
                // If deleted, try to revert the user role
                boolean roleUpdated = ClientController.getUserService().updateRoleToUser(username);

                if (roleUpdated) {
                    JOptionPane.showMessageDialog(this, "User '" + username + "' removed from admins and role reverted to user.");
                } else {
                    JOptionPane.showMessageDialog(this, "User removed from admins but failed to revert role.");
                }

                loadUsersTable(); // Refresh user table
            } else {
                JOptionPane.showMessageDialog(this, "Failed to remove '" + username + "' from admins.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred while removing admin: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a user.");
    }
    }//GEN-LAST:event_removeadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminPanel().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Booked;
    private javax.swing.JTable BookedTable;
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JTable TicketTable;
    private javax.swing.JButton Tickets;
    private javax.swing.JButton Users;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletbtnu;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField destinationTxt;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaReceipt;
    private javax.swing.JButton makeadmin;
    private javax.swing.JTextField orginTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JButton removeadmin;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton searchbtbb;
    private javax.swing.JTextField searchbtxt;
    private javax.swing.JTextField seatTxt;
    private javax.swing.JButton serchbtnu;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables


    
private void loadTicketsToTable() throws RemoteException {
    // Call remote method via RMI to get all tickets
    List<Ticket> tickets = ClientController.getTicketService().readAllTickets();
    // Assuming your JTable is named TicketTable
    DefaultTableModel model = (DefaultTableModel) TicketTable.getModel();
    model.setRowCount(0); // Clear existing rows
    // Populate table with ticket data
    for (Ticket ticket : tickets) {
        model.addRow(new Object[]{
            ticket.getTicketId(),
            ticket.getOrigin(),
            ticket.getDestination(),
            ticket.getDate(),
            ticket.getPrice(),
            ticket.getCategory(),
            ticket.getSeat()
        });
    }
}
  


private void loadUsersTable() {
    try {
        // Get users from remote RMI service
        List<User> users = ClientController.getUserService().getAllUsers();

        // Assuming your JTable is named "userTable"
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        model.setRowCount(0); // Clear table before populating

        for (User user : users) {
            model.addRow(new Object[]{
                user.getUsername(),
                user.getPhoneNumber(),
                user.getAddress(),
                user.getPassword(),
                user.getRole()
            });
        }
    } catch (RemoteException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to load users: " + e.getMessage());
    }
}

    
    
    

private void loadBookedTicketsToTable() {
    try {
        // Fetch booked tickets from remote RMI service
        List<BookedTicket> bookedTickets = ClientController.getBookedTicketService().getAllBookedTickets();

        // Define column names
        String[] columnNames = { "Ticket ID", "Username", "Phone Number", "Address", "Origin", "Destination" };

        // Prepare row data
        Object[][] rowData = new Object[bookedTickets.size()][columnNames.length];

        for (int i = 0; i < bookedTickets.size(); i++) {
            BookedTicket bookedTicket = bookedTickets.get(i);
            rowData[i][0] = bookedTicket.getTicketId();
            rowData[i][1] = bookedTicket.getUsername();
            rowData[i][2] = bookedTicket.getPhoneNumber();
            rowData[i][3] = bookedTicket.getAddress();
            rowData[i][4] = bookedTicket.getOrigin();
            rowData[i][5] = bookedTicket.getDestination();
        }

        // Create and set table model
        DefaultTableModel model = new DefaultTableModel(rowData, columnNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table non-editable
            }
        };

        // Set table model to your JTable
        if (BookedTable != null) {
            BookedTable.setModel(model);
        } else {
            JOptionPane.showMessageDialog(this, "Error: BookedTable is not initialized.");
        }

    } catch (RemoteException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to load booked tickets: " + e.getMessage());
    }
}



    

public void clear(){
    
        orginTxt.setText("");
        destinationTxt.setText("");
        DateTxt.setText("");
        priceTxt.setText("");
        Category.setSelectedIndex(0); // Reset combo box
        seatTxt.setText("");
    
   };

private void makeTableRowsSelectable() {
    BookedTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            int selectedRow = BookedTable.getSelectedRow();
            if (selectedRow != -1) {
                String selectedTicketId = (String) BookedTable.getValueAt(selectedRow, 0);
                String selectedUsername = (String) BookedTable.getValueAt(selectedRow, 1);
                // You can use this data (e.g., for booking confirmation, etc.)
                System.out.println("Selected Ticket ID: " + selectedTicketId + ", Username: " + selectedUsername);
            }
        }

       
    });
}

   
    
  private void displaySelectedTicketDetails(String username, String ticketId) {
    try {
        // Fetch booked tickets remotely by username
        List<BookedTicket> bookedTickets = ClientController.getBookedTicketService().getBookedTicketsByUsername(username);

        if (bookedTickets.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No booked tickets found for printing.");
            return;
        }

        // Find the ticket with the given ticketId
        BookedTicket bookedTicket = null;
        for (BookedTicket ticket : bookedTickets) {
            if (ticket.getTicketId().equals(ticketId)) {
                bookedTicket = ticket;
                break;
            }
        }

        if (bookedTicket != null) {
            // Create the ticket details in the requested format
            String ticketDetails =
                "=================================\n" +
                "          BELAIRLINES\n" +
                "        TICKET RECEIPT\n" +
                "=================================\n\n" +
                "Ticket ID: " + bookedTicket.getTicketId() + "\n\n" +
                "Passenger: " + bookedTicket.getUsername() + "\n\n" +
                "Phone Number: " + bookedTicket.getPhoneNumber() + "\n\n" +
                "Address: " + bookedTicket.getAddress() + "\n\n" +
                "Origin: " + bookedTicket.getOrigin() + "\n\n" +
                "Destination: " + bookedTicket.getDestination() + "\n\n" +
                "Date: " + bookedTicket.getDate() + "\n\n" +
                "Price: $" + String.format("%.2f", bookedTicket.getPrice()) + "\n\n" +
                "Category: " + bookedTicket.getCategory() + "\n\n" +
                "Seat:  " + bookedTicket.getSeat() + "\n\n" +
                "---------------------------------\n" +
                "Thank you for choosing BelairLines!\n" +
                "Contact: +250791822315\n" +
                "www.belairlines.com\n" +
                "=================================\n";

            // Display the ticket details in JTextArea
            jTextAreaReceipt.setText(ticketDetails);
        } else {
            jTextAreaReceipt.setText("Ticket not found.");
        }

    } catch (RemoteException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error retrieving ticket details: " + e.getMessage());
    }
}


   

    



}
