/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import controller.ClientController;
import model.BookedTicket;
import java.awt.Component;
import java.awt.Font;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Ticket;
import service.BookedTicketService;
import service.TicketService;

/**
 *
 * @author Serge B
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    
    private String loggedInUser;
    public Booking(String username ) {
        
         initComponents(); // Initializes components like labels, buttons, etc.
        this.loggedInUser = username;
        // Set the logged-in user label here
        loggedUserLabel.setText("" + username);
        
        
        loadTicketsToTable();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loggedUserLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signout = new javax.swing.JButton();
        home = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        businessR = new javax.swing.JCheckBox();
        economicR = new javax.swing.JCheckBox();
        fistR = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        orginTxt = new javax.swing.JTextField();
        destinationTxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        Bsearch = new javax.swing.JButton();
        booking = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TicketTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome On Booking Page");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        loggedUserLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        loggedUserLabel.setForeground(new java.awt.Color(102, 153, 0));
        loggedUserLabel.setText("Kevine Dev");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/profile.png"))); // NOI18N

        signout.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        signout.setForeground(new java.awt.Color(102, 153, 0));
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/power.png"))); // NOI18N
        signout.setText("Signout");
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });

        home.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(102, 153, 0));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/3d-house.png"))); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        profile.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        profile.setForeground(new java.awt.Color(51, 153, 0));
        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loggedUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signout, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loggedUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signout))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 140));

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/google-maps.png"))); // NOI18N
        jLabel4.setText("ORGIN");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/google-maps.png"))); // NOI18N
        jLabel5.setText("DESTINATION");

        jPanel5.setBackground(new java.awt.Color(255, 204, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 153, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/first-class.png"))); // NOI18N
        jLabel8.setText("Business Class");

        jLabel9.setBackground(new java.awt.Color(255, 204, 102));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 153, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/travel.png"))); // NOI18N
        jLabel9.setText("Economic Class");

        businessR.setBackground(new java.awt.Color(255, 204, 102));
        businessR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessRActionPerformed(evt);
            }
        });

        economicR.setBackground(new java.awt.Color(255, 204, 102));
        economicR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economicRActionPerformed(evt);
            }
        });

        fistR.setBackground(new java.awt.Color(255, 204, 102));
        fistR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fistRActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/passenger.png"))); // NOI18N
        jLabel1.setText("FistClass");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fistR)
                    .addComponent(businessR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addComponent(economicR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fistR))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(businessR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(economicR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(destinationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(423, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Bsearch.setBackground(new java.awt.Color(255, 204, 102));
        Bsearch.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Bsearch.setForeground(new java.awt.Color(102, 153, 0));
        Bsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        Bsearch.setText("Search");
        Bsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsearchActionPerformed(evt);
            }
        });

        booking.setBackground(new java.awt.Color(255, 204, 102));
        booking.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        booking.setForeground(new java.awt.Color(102, 153, 0));
        booking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/booking.png"))); // NOI18N
        booking.setText("BookFlight");
        booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 153, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/airplane.png"))); // NOI18N
        jLabel6.setText("AVAILABLE FLIGHTS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(booking)
                .addGap(87, 87, 87))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booking, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 760, 340));

        jLabel3.setBackground(new java.awt.Color(255, 204, 102));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/airplane-ticket.png"))); // NOI18N
        jLabel3.setText("BOOK TICKET OF YOUR CHOICE");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 350, 48));

        jPanel7.setBackground(new java.awt.Color(255, 204, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TicketTable.setBackground(new java.awt.Color(255, 255, 153));
        TicketTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TicketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "TicketId", "Orgin", "Destination", "Date", "Price", "Class", "Seat"
            }
        ));
        TicketTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TicketTableComponentAdded(evt);
            }
        });
        jScrollPane2.setViewportView(TicketTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 760, 190));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/wind-spring-white-stratosphere-pure_1.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 670));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsearchActionPerformed
      String origin = orginTxt.getText().trim();
    String destination = destinationTxt.getText().trim();
    String category = null;

    // Determine selected category
    if (fistR.isSelected()) {
        category = "First";
    } else if (businessR.isSelected()) {
        category = "Business";
    } else if (economicR.isSelected()) {
        category = "Economic";
    }

    // Check if all fields are filled
    if (origin.isEmpty() || destination.isEmpty() || category == null) {
        JOptionPane.showMessageDialog(this, "Please fill all fields and select a class.");
        return;
    }

    // Use RMI service instead of DAO
    TicketService ticketService = ClientController.getTicketService();
    List<Ticket> result = null;
        try {
            result = ticketService.searchTickets(origin, destination, category);
        } catch (RemoteException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    DefaultTableModel model = (DefaultTableModel) TicketTable.getModel();
    model.setRowCount(0); // Clear table first
    if (result.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No matching tickets found.");
        loadTicketsToTable(); // Load all again
    } else {
        for (Ticket ticket : result) {
            model.addRow(new Object[]{
                ticket.getTicketId(),
                ticket.getOrigin(),
                ticket.getDestination(),
                ticket.getDate(),
                ticket.getPrice(),
                ticket.getCategory(),
                ticket.getSeat()
            });
        }
    }
    this.toFront(); // Bring this window to front
    }//GEN-LAST:event_BsearchActionPerformed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
       int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to log out?",
        "Logout Confirmation",
        JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
        
        LOGIN loginFrame = new LOGIN();
        loginFrame.setVisible(true);
        
        currentFrame.dispose();
    }
    }//GEN-LAST:event_signoutActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        
         JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
        
         Airplane home = new Airplane();
         home.setVisible(true);
         
         currentFrame.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void TicketTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TicketTableComponentAdded
        // TODO add your handling code here:
        
        loadTicketsToTable();
    }//GEN-LAST:event_TicketTableComponentAdded

    private void bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingActionPerformed
         int selectedRow = TicketTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a ticket to book.");
        return;
    }

    // Get ticketId from the selected row
    String ticketId = TicketTable.getValueAt(selectedRow, 0).toString().trim();

    // Get username from UI (e.g., label)
    String username = loggedUserLabel.getText().trim();

    if (username.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Oops, please sign in. No user found!");
        return;
    }

    // Call RMI service to book the ticket
    BookedTicketService bookedService = ClientController.getBookedTicketService();
    boolean success = false;
        try {
            success = bookedService.bookTicket(username, ticketId);
        } catch (RemoteException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    if (success) {
        JOptionPane.showMessageDialog(this, "Ticket booked successfully!");
        
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Ticket booked successfully! Do you want to download your ticket?",
                "Ticket Booking",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE
        );
        
        if (confirm == JOptionPane.YES_OPTION) {
            final String fTicketId = ticketId; final String fUsername = username;
            new Thread(() -> { try { printSelectedTicket(fUsername, fTicketId); } catch (Exception ex) { ex.printStackTrace(); } }).start();
        }




    } else {
        JOptionPane.showMessageDialog(this, "Failed to book ticket. Please try again.");
    }
    }//GEN-LAST:event_bookingActionPerformed

    private void fistRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fistRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fistRActionPerformed

    private void businessRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_businessRActionPerformed

    private void economicRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economicRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_economicRActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        
    JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
    String username = loggedUserLabel.getText();
    
    UserProfile userProfile = new UserProfile(username);
    userProfile.setVisible(true);
    
    currentFrame.dispose();
   
    }//GEN-LAST:event_profileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           String username = ""; 
          new Booking(username).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsearch;
    private javax.swing.JTable TicketTable;
    private javax.swing.JButton booking;
    private javax.swing.JCheckBox businessR;
    private javax.swing.JTextField destinationTxt;
    private javax.swing.JCheckBox economicR;
    private javax.swing.JCheckBox fistR;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel loggedUserLabel;
    private javax.swing.JTextField orginTxt;
    private javax.swing.JButton profile;
    private javax.swing.JButton signout;
    // End of variables declaration//GEN-END:variables

    private void loadTicketsToTable() {
    try {
        // Get the TicketService from RMI
        TicketService ticketService = ClientController.getTicketService();
        List<Ticket> tickets = ticketService.readAllTickets();

        // Get the table model and clear existing rows
        DefaultTableModel model = (DefaultTableModel) TicketTable.getModel();
        model.setRowCount(0);

        // Add each ticket to the table
        tickets.forEach(ticket -> {
            model.addRow(new Object[]{
                ticket.getTicketId(),
                ticket.getOrigin(),
                ticket.getDestination(),
                ticket.getDate(),
                ticket.getPrice(),
                ticket.getCategory(),
                ticket.getSeat()
            });
        });

    } catch (RemoteException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to load tickets: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
 private void printSelectedTicket(String username, String ticketId) throws java.io.IOException {
 try {
 BookedTicketService bookedService = ClientController.getBookedTicketService();
 List<BookedTicket> bookedTickets = bookedService.getBookedTicketsByUsername(username);
 BookedTicket bookedTicket = null;
 for (BookedTicket t : bookedTickets) {
 if (t.getTicket() != null && t.getTicket().getTicketId().equals(ticketId)) { bookedTicket = t; break; }
 }
 if (bookedTicket == null) { javax.swing.SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Ticket not found.")); return; }
 String details = "================================="+System.lineSeparator()+" BELAIRLINES TICKET RECEIPT"+System.lineSeparator()+"================================="+System.lineSeparator()+"Ticket ID : "+bookedTicket.getTicket().getTicketId()+System.lineSeparator()+"Passenger : "+bookedTicket.getUsername()+System.lineSeparator()+"Phone     : "+bookedTicket.getPhoneNumber()+System.lineSeparator()+"Address   : "+bookedTicket.getAddress()+System.lineSeparator()+"Origin    : "+bookedTicket.getTicket().getOrigin()+System.lineSeparator()+"Destination: "+bookedTicket.getTicket().getDestination()+System.lineSeparator()+"Date      : "+bookedTicket.getTicket().getDate()+System.lineSeparator()+"Price     : $"+bookedTicket.getTicket().getPrice()+System.lineSeparator()+"Category  : "+bookedTicket.getTicket().getCategory()+System.lineSeparator()+"Seat      : "+bookedTicket.getTicket().getSeat()+System.lineSeparator()+"================================="+System.lineSeparator()+"Thank you for choosing BelairLines!"+System.lineSeparator();
 String fileName = System.getProperty("user.home")+"\\"+"Ticket_"+ticketId+".txt";
 java.io.FileWriter fw = new java.io.FileWriter(fileName);
 fw.write(details); fw.close();
 final String fn = fileName;
 javax.swing.SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(null, "Ticket saved to: "+fn));
 } catch (RemoteException e) {
 e.printStackTrace();
 javax.swing.SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(null, "Error: "+e.getMessage()));
 }
 }




















































}

