/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.User;

import java.awt.Component;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Serge B
 */
public class Register extends javax.swing.JFrame {

    private Object model;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        firstTxt = new javax.swing.JTextField();
        lastTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 0));
        jLabel2.setText("FirstName");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 22));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 0));
        jLabel4.setText("PhoneNumber");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 110, 26));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 0));
        jLabel5.setText("LastName");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 110, 26));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 153, 0));
        jLabel6.setText("UserName");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 110, 20));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 0));
        jLabel7.setText("Address");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, 26));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 153, 0));
        jLabel8.setText("PassWord");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 26));
        jPanel1.add(firstTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, -1));
        jPanel1.add(lastTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, -1));
        jPanel1.add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, -1));
        jPanel1.add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 170, -1));

        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 170, -1));
        jPanel1.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 280, 170, 30));

        register.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        register.setForeground(new java.awt.Color(102, 153, 0));
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/add.png"))); // NOI18N
        register.setText("Register");
        register.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        cancel.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(102, 153, 0));
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/cancel.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/add-user.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 46, 63));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 0));
        jLabel1.setText("Register To BelAirlines");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 30, 190, 29));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 410, 400));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/istockphoto-619394704-1024x1024.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 720, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
      // Check if any field is empty
    if (firstTxt.getText().isEmpty() || lastTxt.getText().isEmpty() || phoneTxt.getText().isEmpty() ||
        addressTxt.getText().isEmpty() || usernameTxt.getText().isEmpty() || passTxt.getText().isEmpty()) {

        setCustomDialogStyle();
        JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }

    // Validation: First Name (minimum 2 characters)
    if (firstTxt.getText().length() < 2) {
        setCustomDialogStyle();
        JOptionPane.showMessageDialog(this, "First Name must be at least 2 characters long.");
        return;
    }

    // Validation: Last Name (minimum 2 characters)
    if (lastTxt.getText().length() < 2) {
        setCustomDialogStyle();
        JOptionPane.showMessageDialog(this, "Last Name must be at least 2 characters long.");
        return;
    }

    // Validation: Phone Number (valid format)
    String phonePattern = "^[+]?[0-9]{10}$";
    if (!phoneTxt.getText().matches(phonePattern)) {
        setCustomDialogStyle();
        JOptionPane.showMessageDialog(this, "Please enter a valid phone number (10 digits).");
        return;
    }

    // Validation: Address (minimum 10 characters)
    if (addressTxt.getText().length() < 10) {
        setCustomDialogStyle();
        JOptionPane.showMessageDialog(this, "Address must be at least 10 characters long.");
        return;
    }

    // Validation: Password (minimum 6 characters)
    if (passTxt.getText().length() < 6) {
        setCustomDialogStyle();
        JOptionPane.showMessageDialog(this, "Password must be at least 6 characters long.");
        return;
    }

    // Setting model object
    User usr = new User();
    usr.setFirstName(firstTxt.getText());
    usr.setLastName(lastTxt.getText());
    usr.setPhoneNumber(phoneTxt.getText());
    usr.setAddress(addressTxt.getText());
    usr.setUserName(usernameTxt.getText());
    usr.setUserName(usernameTxt.getText());
    usr.setPassword(passTxt.getText()); usr.setRole("user");
    if (controller.ClientController.getUserService() == null) { controller.ClientController.init(); }
    service.UserService userService = controller.ClientController.getUserService();
    try {
        if (userService.usernameExists(usr.getUserName())) {
            setCustomDialogStyle();
            JOptionPane.showMessageDialog(this, "Username already exists! Please choose another one.");
            clearusr();
            return;
        }

        boolean rowAffected = userService.registerUser(usr);
        setCustomDialogStyle();

        if (rowAffected) {
            JOptionPane.showMessageDialog(this, "Your Registration on BelairLines succeeded");
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
            new LOGIN().setVisible(true);
            currentFrame.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Registration failed. Please try again.");
        }
    } catch (java.rmi.RemoteException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "RMI Connection Error: " + e.getMessage());
    }

   
   
        
    }//GEN-LAST:event_registerActionPerformed

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        
         JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor((Component) evt.getSource());
        
         Airplane home = new Airplane();
         home.setVisible(true);
         
         currentFrame.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField firstTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastTxt;
    private javax.swing.JTextField passTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton register;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables

   
    
       private void clearusr() {
       
        usernameTxt.setText("");
        passTxt.setText("");
          
    }
       
       private void setCustomDialogStyle() {
    UIManager.put("OptionPane.background", new Color(255, 255, 153));
    UIManager.put("Panel.background", new Color(255, 255, 153));
    UIManager.put("OptionPane.messageForeground", new Color(0, 100, 0));
    UIManager.put("OptionPane.messageFont", new Font("SansSerif", Font.BOLD, 18));
}

}
